# Generated by Django 4.2.10 on 2024-02-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BDWeather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDWeather.district')),
            ],
        ),
    ]
