# Generated by Django 4.2.10 on 2024-02-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BDWeather', '0002_temperature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temperature',
            new_name='DistTemp',
        ),
    ]
